### ISSUE TITLE
Default PrefetchCount

### ISSUE THREAD

**Issue by JoelGoben** [Particular/NServiceBus.RabbitMQ#100]
The default PrefetchCount is now the MaximumConcurrencyLevel, aka the number of processing threads.  This is a per thread setting though, so if for example 10 threads are configured, the result is that each of the 10 threads prefetches another 10 messages, for a total of 100 prefetched messages.  This seems less than ideal.  The PrefetchCount setting should default to prefetch 1 record per thread.

**Comment by andreasohlund** [comment]
Makes sense now, I got confused by this https://www.rabbitmq.com/consumer-prefetch.html mixing "connection"/ "channel" in a vierd way :(

Since you can configure the prefetch  explicitly, http://docs.particular.net/nservicebus/rabbitmq/configuration-api#configuring-rabbitmq-transport-to-be-used, I assume you're not blocked by this?

**Comment by JoelGoben** [comment]
Correct, I have set PrefetchCount to 1 explicitly, and am not blocked.

**Comment by bording** [comment]
We've made changes to the still-in-progress next version of the transport that will work with the NSB v6 release, and the behavior around the PrefetchCount setting is changing.

With the way the new message pump is designed, we won't need to expose a separate PrefetchCount setting, and will instead rely on the MaximumConcurrency setting to determine what the PrefetchCount should be. We can do this because we're handling concurrency by using a single consumer and the PrefetchCount determines the number of simultaneous in-flight messages.
