### ISSUE TITLE
DefaultRoutingKeyConvention seems to use GetInterfaces.FirstOrDefault incorrectly

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RabbitMQ#11]
@andreasohlund i think there are some problems with this code

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Routing/DefaultRoutingKeyConvention.cs#L21

```
        var interfaces = type.GetInterfaces()
            .Where(i => !IsSystemType(i) && !IsNServiceBusMarkerInterface(i)).ToList();

        var implementedInterface = interfaces.FirstOrDefault();
```

Note we are calling `GetInterfaces` then `.FirstOrDefault();` on that result

The problem is what is returned from `GetInterfaces` is ordered based on the source

For example this 

```
public class MyEvent:IMyInterface1,IMyInterface2
{
}
```

Will return `IMyInterface1` as the first from `GetInterfaces`

While this 

```
public class MyEvent:IMyInterface2,IMyInterface1
{
}
```

Will return `IMyInterface2` as the first from `GetInterfaces`

So from the users perspective their functionality is the same but the routing key will be different.

**Comment by SimonCropp** [comment]
so this is still a bug in deep nested inheritance changes

https://msdn.microsoft.com/en-us/library/system.type.getinterfaces(v=vs.110).aspx

> The GetInterfaces method does not return interfaces in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which interfaces are returned, because that order varies.

**Comment by adamralph** [comment]
The @Particular/rabbitmq-transport-maintainers group discussed this at some length today.

`DefaultRoutingKeyConvention`, as described in the opening comment, is used in `DirectRoutingTopology` only.

The conclusion we came to is that `DirectRoutingTopology` is essentially broken wrt interface based routing. Nor can we think of any way that it could be fixed, since there is no practical way to express an arbitrary number of interfaces for routing via the default exchange.

The only path this leaves open is to remove support for interface based routing in `DirectRoutingTopology`. We also considered whether we should drop `DirectRoutingTopology` entirely, leaving `ConventionalRoutingTopology` (the current default) as the only built-in topology. However, either path would result in a wire-level breaking change (requiring simultaneous upgrade of all endpoints).

In the meantime we believe we should document the limitation and advise against the use of message types which have interfaces in their inheritance hierarchy when using the `DirectRoutingTopology`, instead recommending the use of `ConventionalRoutingTopology` when such routing is required. We also believe it would be useful to log a warning when an interface is being used for routing with `DirectRoutingTopology`.

In summary, we propose the following:

- Raise an issue to be actioned ASAP, for adding an advisory in docs not to use messages types which inherit from non-system interfaces with `DirectRoutingTopology`, advising the use of `ConventionalRoutingTopology` instead.
- Raise an issue to be released in the next minor, to log a warning in `DirectRoutingTopology` when an interface is being used for routing.
- Close ["Make the direct routing topology support multiple inheritance"](https://github.com/Particular/NServiceBus.RabbitMQ/issues/56) as a "won't fix".
- Raise an issue to discuss breaking wire compatibility by either dropping support for interface based routing in `DirectRoutingTopology`, or dropping `DirectRoutingTopology` altogether.

@SimonCropp we'd appreciate any input you have on this.

**Comment by adamralph** [comment]
Raised #268, #269, #270. Closed #56.

**Comment by SimonCropp** [comment]
A couple of things

- place am obsolete message on the offending api and deploy it in a patch
- when that patch is released do a post on the google group about it

**Comment by adamralph** [comment]
Thanks @SimonCropp, those are good ideas. The offending API is the direct routing topology itself and the deprecation and eventual removal of that depends on the outcome of https://github.com/Particular/NServiceBus.RabbitMQ/issues/270, so I'll reference those points from there.
