### ISSUE TITLE
stop endpoint floods log w/ "Reconnecting to the broker failed: System.ObjectDisposedException"

### ISSUE THREAD

**Issue by refactorinc** [Particular/NServiceBus.RabbitMQ#1186]
# description
sometimes when stopping endpoints we observe log flooding

extract below is for 1 endpoint and repeats for >50,000 times/min.
| time | sourcecontext | message |
|--|--|--|
| 13:35:34.000 | NServiceBus.Transport.RabbitMQ.MessagePump | '"UnavailabilityUpdated.Q MessagePump"': Attempting to reconnect in 30 seconds.
13:35:34.000 | NServiceBus.Transport.RabbitMQ.MessagePump | '"UnavailabilityUpdated.Q MessagePump"': Reconnecting to the broker failed: "System.ObjectDisposedException: The CancellationTokenSource has been disposed.<br/>    at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()<br/>    at NServiceBus.Transport.RabbitMQ.MessagePump.Reconnect() in /_/src/NServiceBus.Transport.RabbitMQ/Receiving/MessagePump.cs:line 233" |

# versions tested

- 6.1.4

# impact
- increased cost of log ingest and storage
- high cpu usage during shutdown > leads to delays in shutdown and may cause service unavailability

# who is affected
- potentially all users of the transport

@ramonsmits as discussed during our call

**Comment by ramonsmits** [comment]
Will be fixed in:

- https://github.com/Particular/NServiceBus.RabbitMQ/releases/tag/8.0.1
- https://github.com/Particular/NServiceBus.RabbitMQ/releases/tag/7.0.4
- https://github.com/Particular/NServiceBus.RabbitMQ/releases/tag/6.1.5

Fixes:

- https://github.com/Particular/NServiceBus.RabbitMQ/pull/1190
- https://github.com/Particular/NServiceBus.RabbitMQ/pull/1189
- https://github.com/Particular/NServiceBus.RabbitMQ/pull/1188
- https://github.com/Particular/NServiceBus.RabbitMQ/pull/1186
