### ISSUE TITLE
DirectRoutingTopology "broken" for multiple interfaces

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.RabbitMQ#123]
DirectRoutingTopology should use multiple keys, not one.
It currently can't handle multiple interfaces.

**Comment by mauroservienti** [comment]
should we consider this in scope for V6? if yes, could you please ad the expected label? cheers.

**Comment by andreasohlund** [comment]
:-1: to include in "v6", this has been broken since the dawn of time and the workaround is to pass your own routing topology? ( @johnsimons can you confirm?)

**Comment by bording** [comment]
When using the DirectRoutingTopology, you can pass in your own routing key convention, so in theory an end user could construct their own keys to make their scenario work.

Another workaround is to use the ConventionalRoutingTopology, which is the default. It handles multiple interfaces properly.

Since this has been a problem all along, and not something directly v6-related, it makes sense to hold off on it for now.

We might want to review the docs around this and make sure it explicitly points out this limitation.

**Comment by bording** [comment]
Looking through the issues, I see that this has been brought up before, #11, #56.

Since #56 was around first, I'm going to close this as a dupe.
