### ISSUE TITLE
Enhance code readability and using .NET 8 new features

### ISSUE THREAD

**Issue by nimanikoo** [Particular/NServiceBus.RabbitMQ#1366]
### Describe the suggested improvement

Hi 👋
I hope you are doing well.
I was reviewing the project and noticed that .NET 7 is being used for the latest version.
I also noticed some areas in the code where accessor modifiers could be applied, which might be helpful during code review.
I wanted to ask if you have any plans to upgrade to C# 12 and .NET 8?
If you are agreeable, I would be happy to help with the upgrade and submit a pull request for the changes.
I believe that upgrading to C# 12 and .NET 8 would be a positive step for the project and would make it more efficient, scalable, and future-proof.
Please let me know your thoughts on this proposal.
Thank you

Step 1: I will update all existing modules and projects to .NET 8.
Step 2: I will fix the namespaces and utilize the new features of .NET 8.
Step 3: I will perform a code review file by file to improve readability and refactor the code with references.

I am open to suggestions and feedback.
I will refactor the code to make it more modular and reusable.
I am confident that this upgrade will be a positive step for the project and I look forward to working with you on it.

Thank you for your time and consideration

**Comment by boblangley** [comment]
The .NET 8 release of this transport is coming very soon. Some or all of the work you describe has already been done.

Additionally, and unfortunately, it’s against Israeli law for us to sell or do business with a company or individuals located in certain countries, including answering any questions or accepting code contributions. We really hope this will change one day so that we’ll be able to accept contributions from you in the future.
