### ISSUE TITLE
Lots of skipped causes redelivery in RabbitMQ

### ISSUE THREAD

**Issue by mtherien** [Particular/NServiceBus.RabbitMQ#148]
I have a service that consumes a lot of messages.  The queue fills up to 2 or 3 million at times.

So we removed one of the consumers from the bus and the messages started moving to the "skipped" queue.  However, it seems to run fine for awhile and then stops moving the messages to skipped and then they show up as redelivered.  In seems to be going in a loop.

I looked at the log and see this message when it occurs:
"The connection cannot support any more channels. Consider creating a new connection"

Any suggestions?

**Comment by bording** [comment]
@mtherien What version of the RabbitMQ transport are you currently using? Looks like there was a similar problem in #51, but that was fixed in 2.0.2.

If updating the transport isn't enough to fix your issue, we might need to get further into what your endpoint set up looks like. Do you know if you have a support contract? If so, I could open a ticket for you and we could dig into this more.
