### ISSUE TITLE
Update to Rabbit client 3.6.2

### ISSUE THREAD

**Issue by volak** [Particular/NServiceBus.RabbitMQ#150]
They added a new interface property that is not implemented in NSB's client and again broke assembly scanning where this library is concerned.  

The only way to fix is to downgrade to 3.6.1 and add a redirect from 3.6.2 to 3.6.1

**Comment by bording** [comment]
@volak I'm hoping to have an updated release out soon that will be built against 3.6.2.

**Comment by volak** [comment]
@bording Thanks - perhaps it might be a good idea to change the nuget package dependencies to allow rabbit client max 3.6.2 too.  This is the second time in my short use of their client they have made a breaking change in a minor version..

**Comment by bording** [comment]
We have considered doing that, but the downside of that change is we then **have** to release a new package every time they update, even if/when there aren't breaking changes and it would otherwise work with a binding redirect.

Given that they like to break whenever they feel like it, perhaps that might be best approach.

**Comment by bording** [comment]
While preparing the 3.3.0 release, I caught a bug in the new RabbitMQ client, so I skipped releasing it and built 3.3.1 instead.

**Comment by adamralph** [comment]
@volak this has been fixed in https://www.nuget.org/packages/NServiceBus.RabbitMQ/3.3.1.

Thanks very much for raising this issue!
