### ISSUE TITLE
ObjectDisposedException when Critical Error was triggered

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.RabbitMQ#251]
The CustomChecks SC plugin currently raises a critical error when the SC queue wasn't reachable. When this happens, a ObjectDisposedException occurs in parallel on the MessagePump when `MessagePumpConnectionFailedCircuitBreaker circuitBreaker;` is called here: https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Receiving/MessagePump.cs#L140

It seems that due to the critical error the endpoint is stopped & disposed while `consumer.Registered` is triggered. Dispose doesn't unsubscribe this callback.

How to reproduce:

Create a new endpoint and install the `ServiceControl.Plugin.Nsb6.CustomChecks` Plugin.

```
            EndpointConfiguration config = new EndpointConfiguration("v6");
            config.SendFailedMessagesTo("error");
            config.UsePersistence<InMemoryPersistence>();
            config.UseTransport<RabbitMQTransport>();

            var endpoint = await Endpoint.Start(config);
```

ping @bording

**Comment by bording** [comment]
@timbussmann Following your repro, I am seeing an `ObjectDisposedException`, but it's coming from the MessagePump itself when `Start` is called, not the circuit breaker. It appears that the critical error raised by the plugin during the startup sequence isn't preventing core from continuing to try start the endpoint.

Because there is a race between startup and shutdown, I'm seeing the shutdown go fast enough so that the MessagePump is disposed before `Start` is called, and you're seeing the MessagePump get started first. `Consumer_Registered` is called once on startup, so the error you're seeing must be from the first time the consumer is registered.

Based on that, I don't think there is anything different for the transport do here, and instead this would need to be addressed in core.

**Comment by timbussmann** [comment]
talked last week with @bording and there is little to do to completely avoid all possible race conditions in that case (while unsubscribe the event might avoid one race condition, there are others like those experienced by Brandon). The root cause in the end is the plugin which doesn't throw an exception on the FeatureStartupTask but "swallows" it and raises a criticalError behind. Instead a normal exception would properly stop endpoint startup instead. Closing this issue as it's not a RabbitMQ issue (you might still want to consider to unsubscribe ;) )
