### ISSUE TITLE
Virtual Host isolation in tests has some problems

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RabbitMQ#295]
With the changes made in #275 to make the tests run on a separate virtual host, we have some inconsistent behavior. The Tests project handles the connection string differently from the other two tests projects.

If there is a connection string in the environment variable, the Tests project uses it exactly as is, but the other two projects (and the build script) will modify the value before using it.

For example, I have the following connection string set: "host=rabbit". For the Tests project the virtual host for the tests ends up being the default `/`, but for the other two projects, the lack of a default specified in the environment variable means that those tests run in the `nsb-rabbitmq-test` virtual host.

I'm thinking that we need to not be modifying the connection string specified in the environment variable, aligning all the behavior to how it is in the Tests project. Right now, if I try to run an acceptance test from inside VS, I get a failure because the `nsb-rabbitmq-test` virtual host doesn't exist yet. 

Another somewhat related issue is that if I were to specify `/` as my virtual host explicitly, then the tests would all work correctly from inside VS, but if I ran them through the build script, the build script would be deleting and recreating the default virtual host. While this appears to be allowed, it seems a bit weird to me.

**Comment by adamralph** [comment]
I agree that we need to get rid of the inconsistencies.

IMHO all the tests should use `nsb-rabbitmq-test` by default and the guidance for running the tests within Visual Studio should be:

- Run `.\build.cmd prepare-virtual-host`
- Run the tests

**Comment by adamralph** [comment]
Regardless of what the default host should be, I've had a refactoring floating around in my head for the past week or so which would simplify all of this. I'll have a play around and send a PR.

**Comment by adamralph** [comment]
☝️ #297 is not the refactoring, it merely does the simplest thing possible to remove the inconsistency.

**Comment by bording** [comment]
@adamralph Looking at the change introduced in #297, the more I think I'd prefer to go in the other direction. Here's what I propose:

- If no connection string is defined, stick to the default values as defined by `ConnectionConfiguration`.
- If a connection string is defined, then use it exactly as specified by the user.
- The build scripts virtual host tasks should check to see if the specified connection string has an explicit virtual host set (maybe even look specifically for `nsb-rabbitmq-test`) and only try to delete/create if it exists. Otherwise it should be a no-op.

This would mean that someone who clones the repo would immediately be able to run tests from Visual Studio if they had a newly configured rabbit install on their machine, and wouldn't have to first invoke the build script to make everything work.

Then if, they do want to customize things, they can specify a connection string in the environment variable, and use the build script to handle the virtual host creation.

This also addresses the other issue that I have with the current approach: When a user sets a connection string, we won't be deciding to use some other value than what they specified like we are now. 

Thoughts?

**Comment by adamralph** [comment]
I see two problems with that approach:

- Our tests do not reliably pass if the artifacts they create are already on the virtual host when the tests start running. I'm not sure any more which tests are the culprits, but I do know the symptom is true. Before we had the test isolation in place, I had to drop and recreate the default virtual host manually each time before each complete test run. If I didn't do this, I would get various errors almost every time I ran the tests. On the build server this is handled by resetting the entire broker before each run, but clearly that would be way to invasive for a developer machine. Dropping and recreating a virtual host (or deleting all artifacts) is the next step down from that, but it's again too invasive to perform on the default virtual host. We could investigate clearing out only the specific items that the tests create, but I can see that getting quite messy and out of date due to the code duplication it would probably require.
- Contamination of the default virtual host by default. It feels intrusive of a developers environment. They may be working on other projects that use RabbitMQ, and they may be using the default virtual host for other things. That said, if those other things care about being isolated, then they should use another virtual host themselves. Perhaps if our tests are oblivious to the existence of other artifacts on the default virtual host then we can just use it. The previous point is still a concern though.

> This also addresses the other issue that I have with the current approach: When a user sets a connection string, we won't be deciding to use some other value than what they specified like we are now.

I don't think we're deciding to use other values. We respect whatever values the user sets, and we only fill in the gaps for required values, by masking those values over the defaults. That said, I'm not opposed to changing all the tests so that if the connection string is present, we just use the entire thing.

**Comment by bording** [comment]
> Our tests do not reliably pass if the artifacts they create are already on the virtual host when the tests start running. I'm not sure any more which tests are the culprits, but I do know the symptom is true. 

Interesting. I've never experienced this before when running the tests locally. Given that the tests purge the queues before running, I wouldn't expect this to be a problem. If this is happening, it feels like we should investigate the root cause. To me, the point of wiping the broker before running is to make sure we don't fail the tests because of changes to exchange/queue declarations or subscription bindings.

> I don't think we're deciding to use other values. We respect whatever values the user sets, and we only fill in the gaps for required values, by masking those values over the defaults.

Thinking about it a bit more, I think its the fact that we now have two different default values for the virtual host property, so that the same connection string results in different behavior depending on where it is used. While it's true you'd have to be wanting to run our tests to see this different behavior, it still feels like something we'd want to avoid if possible.

**Comment by WojcikMike** [comment]
Taking a different perspective on test isolation, what if we would use non durable queues, exchanges and simply restart the broker before the tests? Would that simplify things?

**Comment by adamralph** [comment]
Restarting the broker also feels disrespectful of the local environment.

To look at it another way, imagine a web framework which includes IIS hosting. If I cloned the repo and ran the tests, I'd be rather upset if any of the following happened:

- IIS has a factory reset (this is the equivalent of what we do with the RabbitMQ broker during CI)
- IIS is restarted
- the default wwwroot folder is cleared out
- the default wwwroot folder is polluted with test artifacts from the framework

The respectful behaviour would be that the tests run under a dedicated virtual host on the local IIS instance, with it's own physical folder on disk.

That is the equivalent of using a dedicated virtual host on the local RabbitMQ broker.

**Comment by adamralph** [comment]
Discussed in @Particular/rabbitmq-transport-maintainers sync. All concerns have been addressed in #299 and #313.
