### ISSUE TITLE
Rename UseRoutingTopology?

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.RabbitMQ#444]
Should UseRoutingTopology be renamed to UseCustomRoutingTopology instead?

The only usage of that API I was able to find on docs is related to a custom routing topology: https://docs.particular.net/transports/rabbitmq/routing-topology#custom-routing-topology but that's not clear from the API as I had the impression it's a general purpose API which allows me to define any of the existing built-in topologies.

**Comment by adamralph** [comment]
I'm not sure about this. We have to bear in mind that [explicit toplogy choice is now mandatory](https://github.com/Particular/NServiceBus.RabbitMQ/issues/427) and we intend to [deprecate the current topologies](https://github.com/Particular/NServiceBus.RabbitMQ/issues/411) in the 5.x timeframe. That will leave `UseRoutingTopology` as the only method available to choose the new, built-in, topology unless we introduce a `Use{NameToBeDecided}Topology`, but I'm not convinced that we should.

**Comment by WojcikMike** [comment]
As we make using of topology mandatory I would leave the name as is. As now in every transport configuration, `UseRoutingTopology` call will be present with either built-in or custom topology.

**Comment by timbussmann** [comment]
so you're saying in the future users will write something like: `UseRoutingTopology(new ConventionalRoutingTopology())` or how would that look like? Because that's what I was trying to to at first but intellisense didn't show any built-in topology to be used. Only after consulting docs I found the correct way to specify a topology.

**Comment by adamralph** [comment]
Ah, you have point @timbussmann. The built in routing topologies are internal therefore `UseRoutingTopology` cannot be used for the mandatory topology selection. Unless we make the new topology being introduced in https://github.com/Particular/NServiceBus.RabbitMQ/issues/411 public, `UseRoutingTopology` will only ever be useful for selecting custom routing topologies.

@Particular/rabbitmq-transport-maintainers thoughts?

**Comment by bording** [comment]
The problem with making either our existing or potential new routing topologies public in order to use them with `UseRoutingTopology` is that they all have non-default constructors that have to be called.

If you're writing a custom routing topology, then you know what dependencies you have, so you know what to pass in, but we wouldn't want users to have to take on the burden of properly creating the ones we provide in the box.

The reason we currently have separate specific APIs to choose a routing topology is that there are potentially unique configuration settings for each of them.

Thinking about this, I suppose it could make sense to rename `UseRoutingTopology` to `UseCustomRoutingTopology`.
