### ISSUE TITLE
Allow to selectively disable publisher confirms for express messages

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.RabbitMQ#454]
> When using non-durable messaging, consider disabling publisher confirms to improve sending performance at the expense of reliability.

https://docs.particular.net/nservicebus/messaging/non-durable-messaging?version=core_7#effect-on-transports-rabbitmq

but Publisher Confirms can only be disabled globally on the endpoint. 

https://docs.particular.net/transports/rabbitmq/connection-settings#publisher-confirms

Would be nice to be able to do something like

```
var transport = endpointConfiguration.UseTransport<RabbitMQTransport>();
transport.UsePublisherConfirms(true, forExpressMessages: false);
```

For endpoints which mix durable and non-durable delivery.

**Comment by bording** [comment]
@danielmarbach There's not a great way to do that because publisher confirms are configured at the channel level. That would mean we'd need two separate channel pools and have to choose from them on a per-message basis. However, you'd probably not want to acquire/release the channel per-message, especially if/when that batching API shows up in the client.

**Comment by danielmarbach** [comment]
If we consider that with NServiceBus a message should be capturing a business intent wouldn't you say then that this influences whether an intent can be considered durable or not? If that is the case wouldn't that also mean it naturally influences what gets batched together from an end-user code perspective, therefore, a channel per-message type might make sense?

I'm also good if we say that we want clear separation of concerns and in those scenarios, we actually recommend to do a split into multiple endpoints. If that's the case we could document this somehow/somewhere and then close this as won't fix.

**Comment by bording** [comment]
At the RabbitMQ level, message durability and publisher confirms are two separate concepts. Publisher confims control whether or not the broker lets you know it received a message you sent it, and is set on a per-channel basis. Message durability controls whether or not a message sitting in a queue will survive a broker restart or not. and is set on a per-message basis.

Because these are two separate things in the broker, we've currently exposed them as two separate options as well.

If someone has some messages that need confirmation and others that don't, it doesn't seem unreasonable to me to split them into multiple endpoints.

@Particular/rabbitmq-transport-maintainers What do you think?

**Comment by adamralph** [comment]
I'm leaning toward the multiple endpoint solution. It seems less risky than us attempting to abstract this around the way the RabbitMQ client operates.

**Comment by danielmarbach** [comment]
Maybe this warrants a plat dev issue. I don't think we can look at this from a purely technical standpoint. It is not enough to say "we didn't do it because RabbitMQ client". I think we should look at it from a design and message intent perspective. Declaring a message as an express message means that the publisher declares that state is volatile (i.ex. stock exchange updates). Now the question comes do we for some reason encourage customers to split those volatile responsibilities into separate endpoints or not and this should then be the driver for the decision we take here.

**Comment by adamralph** [comment]
👍 to a higher level discussion.

**Comment by WojcikMike** [comment]
@danielmarbach I don't fully follow your last comment:
> Now the question comes do we for some reason encourage customers to split those volatile responsibilities into separate endpoints or not and this should then be the driver for the decision we take here.

I don't think this is a problem here. The actual problem is if I want to use non-durable messages and disable publisher confirms only for this kind of messages how I can accomplish that. 

The above is a an optimization so that publisher confirms are not send when a message is not durable which should make sending of express messages faster. But in fact this are two separate technical concerns. What is more those mechanisms are specific to Rabbit, so I am not sure what higher level discussion will bring to this topic. 

Publisher confirms is a mechanism to inform a client that the message is handled by the broker, this also gives you information can the message be routed to a destination queue. 

Introducing 2nd channel might have performance which has to be measured compared to benefit of disabling publisher confirms. At the moment I can't see how this is higher level discussion. I am fine bringing more people to decide but this is still very much in RabbitMQ realm.

**Comment by danielmarbach** [comment]
Good points @WojcikMike 

Still those two things as they are stated in the doco right now seem to be closely related. Because we mention the publisher confirm together with the express messages. Marking a message as non-durable is a per-message concern. Mentioning publisher confirms there kind of leads down the thought path that I went through or not?  Maybe it is just a matter of slightly twisting the doco.

**Comment by ramonsmits** [comment]
I don't think we should use MSMQ terminology but terminology that is aligned with the native transport or even use a transport-specific attribute or naming convention

**Comment by bording** [comment]
As of version 6.0.0, we have removed the ability disable publisher confirms entirely. We've also adjusted the documentation to no longer mention publisher confirms in the non-durable messaging section.
