### ISSUE TITLE
Message queue has no fifo(first in,first out)

### ISSUE THREAD

**Issue by Varorbc** [Particular/NServiceBus.RabbitMQ#481]
I found that after the NServiceBus server was disconnected from the RabbitMQ server, some of the messages were out of order.
![image](https://user-images.githubusercontent.com/5714438/43567773-6360660e-9665-11e8-8deb-66a3a81ff764.png)

**Comment by dvdstelt** [comment]
Hi @Varorbc,

This question is probably better asked on https://discuss.particular.net/ or via an email to support@particular.net since we monitor those channels better.

To answer this, we don't support ordered delivery of messages since this is very hard, severely limits throughput and doesn't have any benefits. I'd suggest you use a saga to deal with out-of-order-delivery of messages. We have a tutorial on how to deal with this using a saga: https://docs.particular.net/tutorials/nservicebus-sagas/1-getting-started/

Does that help?

Regards,
Dennis

**Comment by Varorbc** [comment]
@dvdstelt  thank you very much
