### ISSUE TITLE
RabbitMq connection drops when rebuilding cluster

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.RabbitMQ#503]
Raised by @devindran in https://github.com/Particular/NServiceBus/issues/5291

> We are seeing an issue several times now where an issue with RabbitMq that requires the cluster to be rebuilt, results in the application hosting NServiceBus not to reconnect after the cluster is rebuilt.
> 
> Steps are as follows:
> 1. NServiceBus instance is connected to RabbitMq
> 2. Some critical fault requires the cluster to be rebuilt. The instance disconnects from RabbitMq
> 3. After the cluster is rebuilt, the connection does not automatically reconnect, or throw any error.
> 4. The result is the application continues to run, but RabbitMq does not show any connections, nor is any messages processed.
> 
> The current workaround is to manually restart the application/endpoint.

**Comment by bording** [comment]
@devindran Can you provide some more information?

What do you mean by "an issue with RabbitMq that requires the cluster to be rebuilt"? Needing to rebuild your cluster sounds like a serious problem that you shouldn't need to be doing all that often.

What version of NServiceBus, NServiceBus.RabbitMQ, and the RabbitMQ client are you using?

Do you have any logs from when this has happened?

**Comment by devindran** [comment]
The most common reason is due to build up of messages on non active queues that causes memory to run out on the boxes hosting RabbitMq, resulting in the cluster being non responsive. It's not an issue with RabbitMq itself, more of an internal issue in my company where copies of queues are being created with no consumers. We are looking to lock this down.

Versions:
NSB: 7.1.4 (seen this with 7.0 as well)
NSB.RabbitMq: 5.0.1
RabbitMQ: 3.6.0

No logs that is of help. I see the circuit breaker getting armed when the cluster goes down, but doesn't disarm when it is rebuilt. 

Normal disconnect logs:
1.  WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for '*queue* MessagePump' is now in the armed state	
2. WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for '*queue* MessagePump' will now be triggered
3. INFO  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for '*queue* MessagePump' is now disarmed

When the cluster is rebuilt:
1. WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for '*queue* MessagePump' is now in the armed state
2. WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for '*queue* MessagePump' will now be triggered

But I never see the disarmed log

**Comment by bording** [comment]
We are relying on the underlying RabbitMQ client's connection recovery behavior in our circuit breaker, so if it is never able to reconnect, then you would never see the endpoint start processing messages again.

The fact that you are seeing this behavior when you've completely rebuilt the cluster leads me to believe that the connection recovery mechanism is not designed to handle something of that magnitude.

However, there is still something you can do to improve this scenario. In the log snippets you provided, you can see that the circuit breaker has triggered. For production endpoints, it's expected that you provide a custom critical error action that is appropriate to your system: https://docs.particular.net/nservicebus/hosting/critical-errors#custom-handling

You should be logging something or even stopping the endpoint process when this occurs, so that you can better detect that the endpoint is in a non-functioning state.

For example, if you're running your endpoints as Windows services, you could kill the process in the and then Windows would restart it for you, allowing the endpoint to successfully connect after you've brought the broker back up.

**Comment by bording** [comment]
@devindran Were you able to make any of the changes I suggested above?

**Comment by bording** [comment]
@devindran I'm going to assume you were able to resolve your issues, but if you're still seeing problems,  feel free to comment or open a support case.
