### ISSUE TITLE
Upgrading NSB + NSB.RabbitMQ causing old Saga Timeouts to fail delivery

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus.RabbitMQ#518]
Hey Guys,

We are upgrading our nservicebus endpoints from Nservicebus 5.x and NServicebus.Rabbitmq 2.x and upgraded these packages both to Nservicebus 7.x and NServiceBus.Rabbitmq 5.x.

Per the documentation, we have enabled the timeout manager for the rabbitmq transport in order to ensure old saga timeouts in ravendb ( not using new delay queues in newer version of the rabbitmq ) get handled by the timeout manager and are not abandoned.

https://docs.particular.net/transports/rabbitmq/delayed-delivery#backwards-compatibility-enabling-the-timeout-manager

What we are noticing is that when the old saga timeouts trigger rabbitmq is trying to send the timeout message to an exchange that doesn't exist.  It's sending the message to an exchange named after the endpoint with the @computername tacked onto the end.  

I've already talked to @boblangley And he mentioned this functionality was removed from the rabbitmq transport a while back.  My Question is

Did we skip a version upgrade that includes a automatic migration to handle this situation?

What do we need to do in order to perform our upgrade and handle old saga timeouts?

/cc @boblangley

**Comment by boblangley** [comment]
We worked with @TraGicCode to resolve this offline, but for anyone else that runs into this in the future I will provide the recommended solution and an explanation of what happened:

We recommend reverting your affected endpoint back to NServiceBus core v5.2.26 and NServiceBus.RabbitMq version v3.5.2 and run each this way for a duration equal to or greater than the longest timeout the endpoint generates. This will allow you to process the existing timeouts that have the anomalous data, while any new timeout data generated will not have this issue.

Here is an explanation of the problem and why we recommend this solution:

During the NServiceBus v5 timeframe addresses were handled internally using [an Address class](https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Address.cs) that included properties for the endpoint queue name and the machine name. This was a hold-over from when NServiceBus only supported MSMQ which requires both pieces of information. This internal class, by default, when converted ToString includes both the endpoint queue name and machine name separated by an `@` symbol. This behavior could be changed by calling the `Address.IgnoreMachineName()` static method.

In NServiceBus.RabbitMQ transport versions earlier than v3.3.2 `IgnoreMachineName` was not invoked. For the most part, the transport worked just fine because it could just use the Address class to parse strings and retrieve the queue name. All of the addresses in the message headers in these earlier versions include the machine name, which requires the Address class to parse correctly.

In NServiceBus core v6 we removed the Address class and began using simple strings. Each transport can then support its own address format and NServiceBus.RabbitMq versions 4 and above only require the queue name to route messages, so `@` notation is not needed and is not supported.

So when a timeout is generated using NServiceBus.RabbitMq versions earlier than 3.3.2, which has header information with the machine name included, is processed by NServiceBus.RabbitMq versions 4 and later the string is accepted as-is which results in an exception stating the Exchange is not found.

This is why reverting back to an earlier version works. You will process the existing anomalous timeouts, which the earlier version can handle, but not generate any additional ones. Eventually, you will have no anomalous timeouts in storage, which will allow later versions of the transport to happily process them.

In general, we recommend keeping your NServiceBus package references up to date, and when you do upgrade, and it has been a while, update one major version at a time. Most of the time this will keep you out of trouble.
