### ISSUE TITLE
Allow users to upconvert native BasicDeliverEventArgs to NServiceBus headers 

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#524]
There used to be a loophole in v5 that allows this by registering a custom message id strategy. 

https://discuss.particular.net/t/manipulation-of-headers-adding-a-new-one-inside-custommessageidstrategy-no-longer-works-in-nservicebus-7-1/988

The current version no longer allows this since we extract headers before extracting the message id. The use case is valid and we should support this.

**Comment by bording** [comment]
The change in order here was required due to the fact that `TransportMessage` in v5 allowed `existingId` to be null and the `Id` property would return the header value first: https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/TransportMessage.cs#L66

`MessageContext` doesn't do this, and requires a non-null `messageId`, so it made sense to change extract the headers first to be able get the value from them.

There is already #103 that talks about ways to make `BasicDeliverEventArgs` available.

**Comment by andreasohlund** [comment]
Should  we close this as a duplicate of #103?

**Comment by bording** [comment]
I think that makes sense, yes.
