### ISSUE TITLE
Support RMQ client 3.4

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#53]
Since 3.4 has breaking changes we need to recompile and put out a new minor with version >= 3.4.

Since the RMQ team is not strict about semver I propose we go

[3.4.0, 3.5.0)

**Comment by andreasohlund** [comment]
I plan to do a 2.1 release soon. Any reason we shouldn't update the client? (3.4 has been out since october 27)

**Comment by johnsimons** [comment]
Has anyone asked for it?

**Comment by SimonCropp** [comment]
well since we r strict on versioning with this lib dont we need to update for anyone to get the fixes in the newest version of rabbit client?

**Comment by SimonCropp** [comment]
http://www.rabbitmq.com/release-notes/README-3.4.0.txt
```
.net client
-----------
enhancements
26130 automatic connection recovery similar to that of the Java client
26208 add APIs to make methods easier to use in nowait mode
26324 introduce an interface for ConnectionFactory
26334 set up stream timeouts as early as possible (thanks to John Oliver)
26199 allow IO and heartbeat to be background threads
25525 allow Subscription class to set explicit consumer tag
26097 add support for nack / reject in Subscription
26122 remove unnecessary lock in Subscription
```

**Comment by johnsimons** [comment]
Well is there any known issue with the current version we are on that affects any of our users?
Or is there anything new in the new version that we want to take advantage of?

**Comment by SimonCropp** [comment]
> Well is there any known issue with the current version

See above

> that affects any of our users

difficult to tell

> Or is there anything new in the new version that we want to take advantage of

perhaps `ConnectionFactory` changes? @andreasohlund

**Comment by johnsimons** [comment]
The way I see it is that there is less risk for us to stay with the version we are familiar with and have been supporting, unless there are compelling reasons to update to latest

**Comment by SimonCropp** [comment]
would prefer to iteratively upgrade to new versions after a safe wait period. in this case 3 months.

Better then someone saying "i need version 3.8" in 6 months and we then do a huge jump.

So I say embrace frequent change with appropriate measures to mitigate the risk.

Also from a consumer perspective they would be safe to assume new version of NSB.RMQ release today should have the the version of the client from several months ago.

Also there is risk in not updating since someone may need to use the 3.4 native API inside an endpoint. Any bugs they have with incompatibly between our expectations of compiling against an older version and the new version would be our problem to fix.

**Comment by andreasohlund** [comment]
I'm with @simoncropp here. We have an extensive test suite that will catch
any major issues. Falling to far behind is a bigger risk imo. Since the
client has been out for 3 month it should be stable and I would expect our
existing users to wanting to update and new users would definitely want to
be on the latest version

I'll include this in the 2.1 release
