### ISSUE TITLE
Allow usage of transient queues

### ISSUE THREAD

**Issue by zlepper** [Particular/NServiceBus.RabbitMQ#555]
RabbitMQ has a principle of transient queues, that is a queue that disappears once there are no more connections. 

We would love to have this for cache busting, or "data distribution", as it's called in your docs. The reason we don't find non-durable queues enough is in auto-scaled scanerios, where we need a queue per instance, queues are no cleaned up automatically when the instances disappear. 

As far as i can see from the code (https://github.com/Particular/NServiceBus.RabbitMQ/blob/master/src/NServiceBus.Transport.RabbitMQ/Routing/ConventionalRoutingTopology.cs#L79), there is no way to mark set "autoDelete = true", as they are hardcoded to false. 

Using the recommended way of doing data distribution, we end up with either a lot of unused queues (If we generate a random id for the queue), or we have to do some woodoo to avoid having two instances use the same queue, which doesn't really work in an auto scaling scenario. 

I have looked at https://github.com/Particular/NServiceBus.RabbitMQ/issues/49, however that only deals with non-durable vs durable queues, not transient/auto-deleted.

**Comment by DavidBoike** [comment]
Hi @zlepper, thanks for the suggestion!

I've raised it with the appropriate group to consider for a future release. However, because I don't want to get your hopes up, you should know that we generally avoid encouraging the use of asynchronous messaging in data distribution scenarios. I can see where perhaps this specific feature might take a little bit of the bite out of that argument though, so it's something we'll have to discuss.

**Comment by zlepper** [comment]
If you (NServiceBus) decides this is something you want, I would not be opposed to try to make a pull request, creating the queues themselves doesn't sound horrible, but I'm more worried about "recreation", in case there is a disconnect, which would cause rabbit to delete the queue.

As far as the actual scenario we are trying to solve, the best alternative would probably be redis or something like that, however due to us being a smaller team, there is quite some reluctance with picking up additional required software, so we generally try to solve it using what we already have available, in this case NServiceBus. (in addition redis does not really run on Windows last I checked).

**Comment by DavidBoike** [comment]
> I'm more worried about "recreation", in case there is a disconnect, which would cause rabbit to delete the queue.

Yep, that’s the failure scenario I’d be worried about introducing as well.

**Comment by SzymonPobiega** [comment]
@zlepper would a custom endpoint set-up procedure solve the problem for you? It seems like the problem you are dealing with is caused by the installer part of NSB, not the actual runtime. You can disable the installers and use RabbitMQ SDK to declare the queue "manually" as auto-delete before starting the endpoint.

**Comment by zlepper** [comment]
@SzymonPobiega if I could hook in before the reconnect attempts, and then provide the sessions, then it should yes.

**Comment by SzymonPobiega** [comment]
@zlepper at this point it is not possible to hook up to the connection manager. I guess that in order to implement that kind of notification scenario with transient queues it would be best to use RabbitMQ SDK directly.

**Comment by helenktsai** [comment]
Hi @zlepper,

After discussing your request, unfortunately our team has decided not to offer this feature due to the aforementioned potential failure scenario. Since recoverability is paramount to our product, we do not believe it is in the best interest of most users to enable auto-deleting of queues.
