### ISSUE TITLE
Support custom connection names

### ISSUE THREAD

**Issue by evolvedlight** [Particular/NServiceBus.RabbitMQ#561]
Currently NServiceBus connects with names like "Publish" or "Administration" or "MessagePump". I'd like to be able to customise this so we can see the service names in the RabbitMq administration.

For example instead of Publish I'd like to see "SampleService Publish" where SampleService is the endpoint name.

**Comment by bording** [comment]
Since an endpoint can have more than one message pump, we do already provide the queue name in the message pump's connection:

![image](https://user-images.githubusercontent.com/753669/68977225-c1d2f080-07c5-11ea-9e25-a8ae610a3846.png)

You are correct that we don't currently include anything in the `Publish` and `Administration` connection names.

However, if you go into the the details for for one of the connections, we do provide the endpoint name there:

![Publish](https://user-images.githubusercontent.com/753669/68977428-3574fd80-07c6-11ea-828e-5e8757c024bc.png)

I can see how having that in the connection list as well could be helpful, though.
