### ISSUE TITLE
Assembly name

### ISSUE THREAD

**Issue by vasyaxparfenov** [Particular/NServiceBus.RabbitMQ#602]
I would like to know why you decided to change name of your assembly from NServiceBus.Transports.RabbitMQ to NServiceBus.Transport.RabbitMQ starting from version 5. With this change it is impossible to use assembly redirect which is widely used for NServiceBus.Core assembly. Was it done deliberately or it was just a typo?

**Comment by indualagarsamy** [comment]
Hi @vasyaxparfenov - the package was named to be consistent with our package naming guidelines. 
For example, our MSMQ package is named [NServiceBus.Transport.Msmq](https://www.nuget.org/packages/NServiceBus.Transport.Msmq/) etc. 

Can you explain your scenario where the assembly redirect might help? As I understand with breaking changes, the asm redirect might not be able to help. Thanks much!

**Comment by vasyaxparfenov** [comment]
Hi @indualagarsamy. You actually renamed assembly itself, rather than package, which has NServiceBus.RabbitMQ name (https://www.nuget.org/packages/NServiceBus.RabbitMQ/). I didn’t find any information about breaking changes for NServiceBus.Transport.RabbitMQ 5 in comparison with NServiceBus.Transports.RabbitMQ 4, only for versions below 3.3. It might have helped in a same way NServiceBus.Core redirect helps to resolve issue when your projects has some dependencies to 3rd party packages which reference earlier versions of NServiceBus.

**Comment by adamralph** [comment]
@vasyaxparfenov I would advise against using assembly redirects to redirect a reference to a newer major version. Our packages follow SemVer, which means a major version indicates breaking changes. So in the general case, I would not expect such an assembly redirect to work. In some circumstances you may get lucky and the redirect may work, but this is not a supported scenario. Indeed, this case demonstrates one example of when this may not work: when we change the assembly name. Because 4 to 5 is a major version, an assembly rename, which is a breaking change, is valid.

**Comment by ramonsmits** [comment]
Closing, answered
