### ISSUE TITLE
Replace IManageRabbitMqConnections with a better extension point

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RabbitMQ#74]
Right now its mixing connections that needs to be managed by the caller and connections managed by the manager it self

@johnsimons suggestion seems resonable: https://github.com/Particular/NServiceBus.RabbitMQ/pull/71#issuecomment-73183801

**Comment by bording** [comment]
In addition to the difference between the Admin connections and the other two, the 4.0 release introduces changes that make this interface even less useful.

The current MessagePump design now manages its own connections (one per pump instance instead of sharing one global connection) so `GetConsumeConnection()` isn't used anymore. That means this interface now has a completely vestigial method.

What was the scenario for exposing this as an extension point? I'm not sure I can see how and end user would be able to provide a meaningfully different enough implementation to warrant keeping this around.

Anyone opposed to me removing this as part of the 4.0 release? At the very least, I should make changes to it to remove `GetConsumeConnection`.

CC: @Particular/transport-maintainers

**Comment by andreasohlund** [comment]
:fire:

**Comment by bording** [comment]
This has now been marked obsolete by 3862c7e485281754aa6fe64cd6c30accf7a97c68.

**Comment by andreasohlund** [comment]
Is there a doco pull to adjust http://docs.particular.net/nservicebus/rabbitmq/configuration-api and the upgrade guide?

**Comment by bording** [comment]
@andreasohlund Not yet. Getting the docs updated for the 4.0 release is the last big thing that still needs work. I'm hoping to coordinate with @WojcikMike soon to start getting that taken care of.

**Comment by WojcikMike** [comment]
@andreasohlund tracked by:
Doco - https://github.com/Particular/docs.particular.net/issues/1356
Upgrade Guide - https://github.com/Particular/docs.particular.net/issues/1357
